model:
  name: '6cells_1hidden'
  n_cells: 6
  hl: 1
---
data:
  src: '../subdata'
  hop: 512
  nfft: 1024
  max_nframes:
  win_size: 100
  tar_size: 25
  batch_size: 64
  ds_size:
  frac: 0.5
---
train:
  optimizer: 'adam'
  lr: 0.001
  epochs: 50
  checkpoints: 'checkpoints'
---
test:
  n_blocks: 20
  sample_src: 'test/sample1.wav'